.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:CLIAbstraction-github| image:: https://img.shields.io/badge/pyTooling-CLIAbstraction-ab47bc.svg?longCache=true&style=flat-square&logo=github&longCache=true&logo=GitHub&labelColor=6a1b9a
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction
.. |SHIELD:png:CLIAbstraction-github| image:: https://raster.shields.io/badge/pyTooling-CLIAbstraction-ab47bc.svg?longCache=true&style=flat-square&logo=github&longCache=true&logo=GitHub&labelColor=6a1b9a
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction

.. # Sourcecode license
.. |SHIELD:svg:CLIAbstraction-src-license| image:: https://img.shields.io/pypi/l/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:CLIAbstraction-src-license| image:: https://img.shields.io/pypi/l/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:CLIAbstraction-tag| image:: https://img.shields.io/github/v/tag/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/tags
.. |SHIELD:png:CLIAbstraction-tag| image:: https://raster.shields.io/github/v/tag/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/tags

.. # GitHub release date
.. |SHIELD:svg:CLIAbstraction-date| image:: https://img.shields.io/github/release-date/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/releases
.. |SHIELD:png:CLIAbstraction-date| image:: https://raster.shields.io/github/release-date/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:CLIAbstraction-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/network/dependents
.. |SHIELD:png:CLIAbstraction-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:CLIAbstraction-gha-test| image:: https://img.shields.io/github/workflow/status/pyTooling/pyTooling.CLIAbstraction/Pipeline/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/actions/workflows/Pipeline.yml
.. |SHIELD:png:CLIAbstraction-gha-test| image:: https://raster.shields.io/github/workflow/status/pyTooling/pyTooling.CLIAbstraction/Pipeline/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:CLIAbstraction-codacy-quality| image:: https://img.shields.io/codacy/grade/3806b49bc754407d900232503a8f7d31?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling.CLIAbstraction
.. |SHIELD:png:CLIAbstraction-codacy-quality| image:: https://raster.shields.io/codacy/grade/3806b49bc754407d900232503a8f7d31?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling.CLIAbstraction

.. # Codacy - coverage
.. |SHIELD:svg:CLIAbstraction-codacy-coverage| image:: https://img.shields.io/codacy/coverage/3806b49bc754407d900232503a8f7d31?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling.CLIAbstraction
.. |SHIELD:png:CLIAbstraction-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/3806b49bc754407d900232503a8f7d31?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/pyTooling/pyTooling.CLIAbstraction

.. # Codecov - coverage
.. |SHIELD:svg:CLIAbstraction-codecov-coverage| image:: https://img.shields.io/codecov/c/github/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyTooling.CLIAbstraction
.. |SHIELD:png:CLIAbstraction-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/pyTooling/pyTooling.CLIAbstraction

.. # Libraries - source rank
.. |SHIELD:svg:CLIAbstraction-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling.CLIAbstraction/sourcerank
.. |SHIELD:png:CLIAbstraction-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling.CLIAbstraction/sourcerank

.. # PyPI tag
.. |SHIELD:svg:CLIAbstraction-pypi-tag| image:: https://img.shields.io/pypi/v/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyTooling.CLIAbstraction/
.. |SHIELD:png:CLIAbstraction-pypi-tag| image:: https://raster.shields.io/pypi/v/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyTooling.CLIAbstraction/

.. # PyPI project status
.. |SHIELD:svg:CLIAbstraction-pypi-status| image:: https://img.shields.io/pypi/status/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:CLIAbstraction-pypi-status| image:: https://raster.shields.io/pypi/status/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:CLIAbstraction-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:CLIAbstraction-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:CLIAbstraction-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling.CLIAbstraction
.. |SHIELD:png:CLIAbstraction-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyTooling.CLIAbstraction?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/pyTooling/pyTooling.CLIAbstraction

.. # Requires - status
.. |SHIELD:svg:CLIAbstraction-req-status| image:: https://img.shields.io/requires/github/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/pyTooling/pyTooling.CLIAbstraction/requirements/?branch=main
.. |SHIELD:png:CLIAbstraction-req-status| image:: https://raster.shields.io/requires/github/pyTooling/pyTooling.CLIAbstraction?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/pyTooling/pyTooling.CLIAbstraction/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:CLIAbstraction-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: License.html
.. |SHIELD:png:CLIAbstraction-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/pyTooling/pyTooling.CLIAbstraction/blob/main/doc/License.rst

.. # GHPages - read now
.. |SHIELD:svg:CLIAbstraction-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2FpyTooling.CLIAbstraction&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2FpyTooling.CLIAbstraction%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/pyTooling.CLIAbstraction/
.. |SHIELD:png:CLIAbstraction-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=pyTooling.github.io%2FpyTooling.CLIAbstraction&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2FpyTooling.github.io%2FpyTooling.CLIAbstraction%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://pyTooling.github.io/pyTooling.CLIAbstraction/

.. # Gitter
.. |SHIELD:svg:CLIAbstraction-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:CLIAbstraction-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
